// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLJMY9qzrkfTsy0eeWpKEKngMKepdVko',
    appId: '1:1024629813040:web:8a8cb507f711b3c8f6a2f5',
    messagingSenderId: '1024629813040',
    projectId: 'beholder-companion',
    authDomain: 'beholder-companion.firebaseapp.com',
    databaseURL: 'https://beholder-companion-default-rtdb.firebaseio.com',
    storageBucket: 'beholder-companion.appspot.com',
    measurementId: 'G-N2QQPGK7B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmESCF2N12GjuzDcquL8GPyKmPH-ghYtw',
    appId: '1:1024629813040:android:96ced21c5cccef41f6a2f5',
    messagingSenderId: '1024629813040',
    projectId: 'beholder-companion',
    databaseURL: 'https://beholder-companion-default-rtdb.firebaseio.com',
    storageBucket: 'beholder-companion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGHAgWHHsetI5OFGoOB23XhpfdzHdkIs',
    appId: '1:1024629813040:ios:0648b96b0a054b53f6a2f5',
    messagingSenderId: '1024629813040',
    projectId: 'beholder-companion',
    databaseURL: 'https://beholder-companion-default-rtdb.firebaseio.com',
    storageBucket: 'beholder-companion.appspot.com',
    iosClientId: '1024629813040-ll7r3dnm5ad88bukq54te4vljohq9244.apps.googleusercontent.com',
    iosBundleId: 'com.beholder.beholderCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjGHAgWHHsetI5OFGoOB23XhpfdzHdkIs',
    appId: '1:1024629813040:ios:0648b96b0a054b53f6a2f5',
    messagingSenderId: '1024629813040',
    projectId: 'beholder-companion',
    databaseURL: 'https://beholder-companion-default-rtdb.firebaseio.com',
    storageBucket: 'beholder-companion.appspot.com',
    iosClientId: '1024629813040-ll7r3dnm5ad88bukq54te4vljohq9244.apps.googleusercontent.com',
    iosBundleId: 'com.beholder.beholderCompanion',
  );
}
